import java.util.Scanner;
    public class RUBIN_ACTIVITY_II{
     public static void main(String[] args){
        Scanner input = new Scanner.(Sytem.in);

        System.out.printIn( "Enter first numbaer");
        int num = scanner.nextLine();
        System.out.printIn( "Enter second numbaer");
        int num = scanne.nextLine();

        int sum = firsNumber + secondNumber;
        int diffence = firstNumber - secondNumber;
        int product = firstNumber * secondNumber;
        
        System.out.printIn("sum = " + sum);
        System.out.printIn("difference = " + difference);
        System.out.printIn("product = " + product);
        

    }
  
}   

